# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-21 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0002_master_course_data_master_medium_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_subject_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_date', models.CharField(max_length=20, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data')),
            ],
        ),
    ]
