# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-25 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0004_master_catbook_data_master_subcatbook_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_book_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100, null=True)),
                ('subbook_title', models.CharField(max_length=20, null=True)),
                ('ISBN', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=20, null=True)),
                ('editor', models.CharField(max_length=100, null=True)),
                ('series', models.CharField(max_length=20, null=True)),
                ('publication_year', models.CharField(max_length=100, null=True)),
                ('edition', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('pages', models.CharField(max_length=20, null=True)),
                ('copies', models.CharField(max_length=100, null=True)),
                ('created_date', models.CharField(max_length=20, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_catbook_data')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_subcatbook_data')),
            ],
        ),
    ]
