# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-25 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0005_master_book_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_book_data',
            name='created_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_book_data',
            name='edition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_book_data',
            name='pages',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_book_data',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_book_data',
            name='series',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_book_data',
            name='subbook_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
