# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0011_master_holiday_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_holiday_data',
            name='reason',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
