# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-06 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0015_auto_20180928_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_driver_data',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
