# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-08 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0016_master_driver_data_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_fee_type_data',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data'),
        ),
        migrations.AddField(
            model_name='master_fee_type_data',
            name='fee',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
