# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-08 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0017_auto_20181008_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_asign_bus_data',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_area_data'),
        ),
    ]
