# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-08 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0019_auto_20181008_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_fee_type_data',
            name='course',
        ),
        migrations.RemoveField(
            model_name='master_fee_type_data',
            name='fee',
        ),
    ]
