# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-09 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0020_auto_20181008_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_fee_packege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=100, null=True)),
                ('fee', models.CharField(max_length=100, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data')),
            ],
        ),
    ]
