# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-09 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0021_master_fee_packege'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Master_fee_packege',
            new_name='Master_fee_packege_data',
        ),
    ]
