# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-26 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0022_auto_20181009_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_E_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('created_date', models.CharField(max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_catbook_data')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_subcatbook_data')),
            ],
        ),
    ]
