# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-26 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0023_master_e_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_e_book',
            name='book',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
