# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-26 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0025_register_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library_Issue_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(blank=True, max_length=50, null=True)),
                ('Due', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('Return', models.CharField(blank=True, max_length=50, null=True)),
                ('late_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_book_data')),
                ('StudentHome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institute.Register_Student')),
            ],
        ),
    ]
