# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-26 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0026_library_issue_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libraryfine', models.CharField(blank=True, max_length=20, null=True)),
                ('latefeefine', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
