# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-26 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0027_latefine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_fee_type_packege_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=100, null=True)),
                ('fee', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master_make_installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_1', models.CharField(max_length=100, null=True)),
                ('installment_2', models.CharField(max_length=100, null=True)),
                ('installment_3', models.CharField(max_length=100, null=True)),
                ('installment_4', models.CharField(max_length=100, null=True)),
                ('installment_5', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master_monthly_installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_month', models.CharField(max_length=100, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('fee', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='master_fee_packege_data',
            old_name='fee',
            new_name='discount_for_single',
        ),
        migrations.RenameField(
            model_name='master_fee_packege_data',
            old_name='fee_type',
            new_name='discount_group_11_20',
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='discount_group_2_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='discount_group_6_11',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='discount_group_more_20',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='i_discount_for_single',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='i_discount_group_11_20',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='i_discount_group_2_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='i_discount_group_6_11',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='i_discount_group_more_20',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='installment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='m_discount_for_single',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='m_discount_group_11_20',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='m_discount_group_2_5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='m_discount_group_6_11',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='m_discount_group_more_20',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='monthly_install',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_fee_packege_data',
            name='one_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='master_monthly_installment',
            name='packege',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_fee_packege_data'),
        ),
        migrations.AddField(
            model_name='master_make_installment',
            name='packege',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_fee_packege_data'),
        ),
        migrations.AddField(
            model_name='master_fee_type_packege_data',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_fee_packege_data'),
        ),
    ]
