# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-27 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='que',
            new_name='Question',
        ),
    ]
