# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-28 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0002_auto_20181027_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Questions',
        ),
    ]
