# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-28 09:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0028_auto_20181026_1354'),
        ('ExamPanel', '0003_auto_20181028_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bloging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAffairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('files', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='DealyPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to=b'')),
                ('fee', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('syllabus', models.FileField(null=True, upload_to=b'')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('fee', models.CharField(blank=True, max_length=10, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to=b'')),
                ('syllabus', models.FileField(null=True, upload_to=b'')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('syllabus', models.FileField(null=True, upload_to=b'')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.ExamPackage')),
            ],
        ),
        migrations.CreateModel(
            name='MainExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('instruction', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('syllabus', models.FileField(null=True, upload_to=b'')),
                ('Sub_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.ExamSubPackage')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type1', models.BooleanField(default=False)),
                ('Type2', models.BooleanField(default=False)),
                ('Option1', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Option2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Option3', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Option4', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Answer3', models.BooleanField(default=False)),
                ('Answer4', models.BooleanField(default=False)),
                ('Type3', models.BooleanField(default=False)),
                ('Answer1', models.CharField(blank=True, max_length=250, null=True)),
                ('Answer2', models.CharField(blank=True, max_length=250, null=True)),
                ('Type4', models.BooleanField(default=False)),
                ('Question', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('TrueAns', models.CharField(choices=[['1', 'True'], ['2', 'False']], default='1', max_length=5)),
                ('marks', models.CharField(blank=True, max_length=5, null=True)),
                ('minus', models.CharField(default=0, max_length=20)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.MainExam')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('syllabus', models.FileField(null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='QuizPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to=b'')),
                ('fee', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('syllabus', models.FileField(null=True, upload_to=b'')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data')),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('syllabus', models.FileField(null=True, upload_to=b'')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.QuizPackage')),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.QuizPackage'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='practice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.Topic'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.Quiz'),
        ),
        migrations.AddField(
            model_name='currentaffairs',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.StudyMaterial'),
        ),
        migrations.AddField(
            model_name='bloging',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.StudyMaterial'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.Bloging'),
        ),
    ]
