# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-28 09:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0004_auto_20181028_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicequestions',
            old_name='marks',
            new_name='marks1',
        ),
        migrations.RenameField(
            model_name='multiplechoicequestions',
            old_name='minus',
            new_name='minus1',
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='Answer31',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='Answer32',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='Option_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='Option_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='Option_3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='Option_4',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='Que',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='Ques_tion',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='Questions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='marks2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='marks3',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='marks4',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='minus2',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='minus3',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='minus4',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestions',
            name='Answer1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestions',
            name='Answer2',
            field=models.BooleanField(default=False),
        ),
    ]
