# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-29 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0005_auto_20181028_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.Bloging'),
        ),
        migrations.AlterField(
            model_name='bloging',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.StudyMaterial'),
        ),
        migrations.AlterField(
            model_name='currentaffairs',
            name='files',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='currentaffairs',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.StudyMaterial'),
        ),
        migrations.AlterField(
            model_name='dealypractice',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data'),
        ),
        migrations.AlterField(
            model_name='dealypractice',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dealypractice',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='exampackage',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data'),
        ),
        migrations.AlterField(
            model_name='exampackage',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='exampackage',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='examsubpackage',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.ExamPackage'),
        ),
        migrations.AlterField(
            model_name='examsubpackage',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainexam',
            name='Sub_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.ExamSubPackage'),
        ),
        migrations.AlterField(
            model_name='mainexam',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestions',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.MainExam'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestions',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.Topic'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestions',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.Quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.QuizPackage'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='quizpackage',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data'),
        ),
        migrations.AlterField(
            model_name='quizpackage',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='quizpackage',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='topic',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.QuizPackage'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
