# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-29 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0007_auto_20181029_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.Bloging'),
        ),
        migrations.AlterField(
            model_name='bloging',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.StudyMaterial'),
        ),
        migrations.AlterField(
            model_name='currentaffairs',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.StudyMaterial'),
        ),
        migrations.AlterField(
            model_name='dealypractice',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institute.Master_course_data'),
        ),
        migrations.AlterField(
            model_name='examsubpackage',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.ExamPackage'),
        ),
        migrations.AlterField(
            model_name='mainexam',
            name='Sub_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.ExamSubPackage'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestions',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.MainExam'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestions',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.Topic'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestions',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.Quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.QuizPackage'),
        ),
        migrations.AlterField(
            model_name='quizpackage',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Institute.Master_course_data'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.QuizPackage'),
        ),
    ]
