# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-29 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0008_auto_20181029_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='TrueAns1',
            field=models.CharField(choices=[['1', 'True'], ['2', 'False']], default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestions',
            name='TrueAns',
            field=models.CharField(choices=[['1', '1'], ['2', '2'], ['3', '3'], ['4', '4']], default='1', max_length=5),
        ),
    ]
