# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-01 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0010_auto_20181030_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainExamSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.MainExam')),
            ],
        ),
    ]
