# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-01 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0011_mainexamsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestions',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.MainExamSection'),
        ),
    ]
