# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-03 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0012_multiplechoicequestions_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubpackage',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.ExamPackage'),
        ),
        migrations.AlterField(
            model_name='mainexam',
            name='Sub_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.ExamSubPackage'),
        ),
        migrations.AlterField(
            model_name='mainexamsection',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.MainExam'),
        ),
    ]
