# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-04 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0013_auto_20181203_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package_Subpackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.ExamPackage')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.ExamSubPackage')),
            ],
        ),
        migrations.CreateModel(
            name='SubPackage_MainExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.MainExam')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamPanel.Package_Subpackage')),
            ],
        ),
    ]
