# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-04 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0014_package_subpackage_subpackage_mainexam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsubpackage',
            name='package',
        ),
    ]
