# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-04 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0029_auto_20181204_1146'),
        ('ExamPanel', '0015_remove_examsubpackage_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubpackage',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data'),
        ),
        migrations.AddField(
            model_name='mainexam',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data'),
        ),
    ]
