# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamPanel', '0017_remove_mainexam_sub_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_subpackage',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.ExamPackage'),
        ),
        migrations.AlterField(
            model_name='package_subpackage',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.ExamSubPackage'),
        ),
        migrations.AlterField(
            model_name='subpackage_mainexam',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.MainExam'),
        ),
        migrations.AlterField(
            model_name='subpackage_mainexam',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExamPanel.Package_Subpackage'),
        ),
    ]
