# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-12 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Institute', '0022_auto_20181009_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front_student_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dob', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(max_length=500, null=True)),
                ('mobile', models.CharField(max_length=13, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('college', models.CharField(max_length=100, null=True)),
                ('graduation', models.CharField(max_length=100, null=True)),
                ('stream', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('Father_name', models.CharField(max_length=100, null=True)),
                ('father_mob', models.CharField(max_length=13, null=True)),
                ('Occupation', models.CharField(max_length=100, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('total_fee', models.CharField(max_length=100, null=True)),
                ('first_installment', models.CharField(max_length=100, null=True)),
                ('second_installment', models.CharField(max_length=100, null=True)),
                ('install_last_date', models.CharField(max_length=100, null=True)),
                ('addmission_date', models.CharField(max_length=100, null=True)),
                ('Batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_batch_data')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data')),
            ],
        ),
    ]
