# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-12 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_student_data',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
