# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-13 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontdesk', '0002_auto_20181012_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_student_data',
            name='course',
            field=models.ForeignKey(default='Courses', null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data'),
        ),
    ]
