# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-14 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontdesk', '0007_auto_20181013_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_student_data',
            name='gender',
            field=models.CharField(choices=[('', 'Gender'), ('male', 'Male'), ('female', 'Female')], default='Gender', max_length=10),
        ),
    ]
