# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-14 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontdesk', '0008_auto_20181014_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_student_data',
            name='father_add',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
