# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-16 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Institute', '0022_auto_20181009_1032'),
        ('Frontdesk', '0009_front_student_data_father_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front_enquiry_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('college', models.CharField(max_length=100, null=True)),
                ('graduation', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=13, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('follow_up_date', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=500, null=True)),
                ('visited_date', models.CharField(max_length=100, null=True)),
                ('course', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Institute.Master_course_data')),
            ],
        ),
    ]
