# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontdesk', '0010_front_enquiry_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_enquiry_data',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='front_enquiry_data',
            name='follow_up_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
